apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
  labels:
    app: devops-app
    tier: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
        tier: backend
    spec:
      containers:
        - name: devops-app
          image: srivighnateja/devops-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
